services:
    bruninoit.tipster.listener:
        class: bruninoit\tipster\event\listener
        arguments:
            - @config
            - @dbal.conn
            - @template
            - @auth
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }ù
    bruninoit.tipster.core:
        class: bruninoit\tipster\core\helper
        arguments:
            - @dbal.conn
            - @user
            - @controller.helper
            - @template
    bruninoit.tipster.controller:
        class: bruninoit\tipster\controller\classifica_tipster
        arguments:
            - @dbal.conn
            - @user
            - @config
            - @controller.helper
            - @template
            - %core.root_path%
